name: Build macOS Raylib Game

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Raylib
      run: brew install raylib

    - name: Compile the Game
      run: |
        clang++ main.cpp -std=c++11 -o ttt-mac \
          -I/opt/homebrew/include \
          -L/opt/homebrew/lib \
          -lraylib \
          -framework OpenGL -framework Cocoa -framework IOKit -framework CoreVideo

    - name: Zip the output
      run: zip ttt-mac.zip ttt-mac

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: macOS-Build
        path: ttt-mac.zip
